language: node_js
node_js:
  - 0.6
notifications:
  email:
    on_success: change
    on_failure: always
  irc:
    - "irc.freenode.net#Jolt"
    - "irc.freenode.net#projexsys"
    on_success: always
    on_failure: always

