notifications:
  email:
    on_success: never
    on_failure: always
  irc:
    - "irc.freenode.org#Jolt"
    - "irc.freenode.org#projexsys"
    on_success: always
    on_failure: always
language: node_js
node_js:
  - 0.6.4
